server:
  port: 9092
spring:
 application:
  name: order
 datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12712947
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sql12712947
    password: Wygs35Nzqf
    hikari:
      # Consider these connection pool settings for better performance
      poolName: HikariPool
      minimumIdle: 5
      maximumPoolSize: 10
      autoCommit: true
 jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
