# src/main/resources/application.yml

server:
  port: 8083

spring:
  application:
    name: account-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

cloud:
  openfeign:
    circuitbreaker:
      enabled: true

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org:
     springframework:
      data:
       mongodb:
        core: debug
    mongodb:
     driver: debug

---
spring:
  application:
    name: account-service
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

   


eureka:
  client:
    enabled: false # Disable Eureka client in test profile

logging:
  level:
    root: info
    org:
     springframework:
      data:
       mongodb:
        core: debug
    mongodb:
     driver: debug
