
server:
  port: 9010

spring:
  application:
    name: "Notifications"
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: netfreakerr@gmail.com
#    password: wemkwehlmqnjmzbt  
  
    
  cloud:
    function:
      definition: productcreated
    stream:
      bindings:
        productcreated-in-0:
          destination: sendCommunicationAsProductCreated
          group: ${spring.application.name}
        productcreated-out-0:
          destination: communication-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s